name: Update News Cron
on:
  schedule:
    - cron: '*/30 * * * *' # Ejecutar cada 30 minutos
  workflow_dispatch: # Permite ejecución manual desde GitHub

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call API Route
        run: |
          curl -X GET "${{ secrets.ROUTE_INGEST_URL }}" \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"
