name: Update News Cron
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call API Route
        env:
          VERCEL_URL: ${{ secrets.VERCEL_URL }}
        run: |
          curl -X GET $VERCEL_URL \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"
